# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{belongs_to_city}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adrian Cuadros"]
  s.date = %q{2010-05-17}
  s.description = %q{Creates the basic structure to enable autocomplete search for city-able models in rails 2.3.x}
  s.email = %q{adrian@innku.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "README.textile",
     "Rakefile",
     "VERSION",
     "belongs_to_city.gemspec",
     "generators/belongs_to_city/belongs_to_city_generator.rb",
     "generators/belongs_to_city/templates/migrate/create_belongs_to_city_tables.rb",
     "generators/belongs_to_city/templates/models/city.rb",
     "generators/belongs_to_city/templates/models/country.rb",
     "generators/belongs_to_city/templates/models/state.rb",
     "lib/belongs_to_city.rb",
     "poc/test/README",
     "poc/test/Rakefile",
     "poc/test/app/controllers/application_controller.rb",
     "poc/test/app/helpers/application_helper.rb",
     "poc/test/config/boot.rb",
     "poc/test/config/database.yml",
     "poc/test/config/environment.rb",
     "poc/test/config/environments/development.rb",
     "poc/test/config/environments/production.rb",
     "poc/test/config/environments/test.rb",
     "poc/test/config/initializers/backtrace_silencers.rb",
     "poc/test/config/initializers/inflections.rb",
     "poc/test/config/initializers/mime_types.rb",
     "poc/test/config/initializers/new_rails_defaults.rb",
     "poc/test/config/initializers/session_store.rb",
     "poc/test/config/locales/en.yml",
     "poc/test/config/routes.rb",
     "poc/test/db/seeds.rb",
     "poc/test/log/development.log",
     "poc/test/log/production.log",
     "poc/test/log/server.log",
     "poc/test/log/test.log",
     "poc/test/public/404.html",
     "poc/test/public/422.html",
     "poc/test/public/500.html",
     "poc/test/public/favicon.ico",
     "poc/test/public/images/rails.png",
     "poc/test/public/index.html",
     "poc/test/public/javascripts/application.js",
     "poc/test/public/javascripts/controls.js",
     "poc/test/public/javascripts/dragdrop.js",
     "poc/test/public/javascripts/effects.js",
     "poc/test/public/javascripts/prototype.js",
     "poc/test/public/robots.txt",
     "poc/test/script/about",
     "poc/test/script/console",
     "poc/test/script/dbconsole",
     "poc/test/script/destroy",
     "poc/test/script/generate",
     "poc/test/script/performance/benchmarker",
     "poc/test/script/performance/profiler",
     "poc/test/script/plugin",
     "poc/test/script/runner",
     "poc/test/script/server",
     "poc/test/test/performance/browsing_test.rb",
     "poc/test/test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/adriancuadros/belongs_to_city}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Eases integrating city autocomplete feature to rails application}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

