# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{belongs_to_city}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adrian Cuadros"]
  s.date = %q{2010-05-21}
  s.description = %q{Creates the basic structure to enable City structure integration with any model and eases autocomplete search}
  s.email = %q{adrian@innku.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "belongs_to_city.gemspec",
     "generators/belongs_to_city/USAGE",
     "generators/belongs_to_city/belongs_to_city_generator.rb",
     "generators/belongs_to_city/lib/insert_routes.rb",
     "generators/belongs_to_city/templates/belongs_to_city_tasks.rake",
     "generators/belongs_to_city/templates/cities.csv",
     "generators/belongs_to_city/templates/controllers/cities_controller.rb",
     "generators/belongs_to_city/templates/countries.csv",
     "generators/belongs_to_city/templates/migrate/create_belongs_to_city_tables.rb",
     "generators/belongs_to_city/templates/models/city.rb",
     "generators/belongs_to_city/templates/models/country.rb",
     "generators/belongs_to_city/templates/models/state.rb",
     "generators/belongs_to_city/templates/states.csv",
     "generators/belongs_to_city/templates/views/index.js.erb",
     "lib/belongs_to_city.rb"
  ]
  s.homepage = %q{http://github.com/adriancuadros/belongs_to_city}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Eases integrating a city database structure with any model in rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<searchlogic>, [">= 0"])
      s.add_development_dependency(%q<fastercsv>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<searchlogic>, [">= 0"])
      s.add_dependency(%q<fastercsv>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<searchlogic>, [">= 0"])
    s.add_dependency(%q<fastercsv>, [">= 0"])
  end
end

